# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        os: [win, osx, linux]
        arch: [x64, arm64]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore -r ${{ matrix.os }}-${{ matrix.arch }}
    - name: Build
      run: dotnet build PhpVersionManager/PhpVersionManager.csproj -r ${{ matrix.os }}-${{ matrix.arch }} --no-restore -c Release
    - name: Publish
      run: dotnet publish PhpVersionManager/PhpVersionManager.csproj -r ${{ matrix.os }}-${{ matrix.arch }} --no-build -o publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: build-${{ matrix.os }}-${{ matrix.arch }}
        path: publish/
        if-no-files-found: error
